subscribers:

  camera_reading:
    topic: /stereo/right/image_raw
    queue_size: 2

actions:

  camera_reading:
    name: /right_camera/darknet_ros/check_for_objects

publishers:

  object_detector:
    topic: /right_camera/darknet_ros/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /right_camera/darknet_ros/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /right_camera/darknet_ros/detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: false
  wait_key_delay: 1
  enable_console_output: false
